export const POST_VOUCHER = "POST_VOUCHER";
export const POST_VOUCHER_SUCCESS = "POST_VOUCHER_SUCCESS";
export const POST_VOUCHER_ERROR = "POST_VOUCHER_ERROR";

export const SET_INFO_ALERT = "SET_INFO_ALERT";
export const SET_ERROR_ALERT = "SET_ERROR_ALERT";
export const RESET_ALERT = "RESET_ALERT";
